services:
  controller:
    build: .
    command: python src/controller.py
    ports:
      - "50050:50050"
    environment:
      - CONTROLLER_PORT=50050

  storage-primary:
    build: .
    command: python src/storage_node.py
    environment:
      - CONTROLLER_HOST=controller
      - NODE_PORT=50051
      - POD_IP=storage-primary
      - PEER_ADDRESSES=storage-backup:50051
    depends_on:
      - controller

  storage-backup:
    build: .
    command: python src/storage_node.py
    environment:
      - CONTROLLER_HOST=controller
      - NODE_PORT=50051
      - POD_IP=storage-backup
      - PEER_ADDRESSES=storage-primary:50051
    depends_on:
      - controller

  service-node:
    build: .
    command: python src/service_node.py
    ports:
      - "50052:50052"
    environment:
      - CONTROLLER_HOST=controller
      - NODE_PORT=50052
    depends_on:
      - controller

  envoy:
    image: envoyproxy/envoy:v1.28-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080" # This is the port your React app will talk to
    depends_on:
      - service-node