apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: blindsided
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.28-latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: envoy-config-volume
          mountPath: /etc/envoy
      volumes:
      - name: envoy-config-volume
        configMap:
          name: envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-svc
  namespace: blindsided
spec:
  selector:
    app: envoy
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort