apiVersion: v1
kind: Service
metadata:
  name: storage-service
spec:
  clusterIP: None
  selector:
    app: storage
  ports:
    - port: 50051
      name: grpc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage
spec:
  serviceName: "storage-service"
  replicas: 2
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: storage-node
        image: marketplace-app:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "src.storage_node"]
        env:
        - name: CONTROLLER_HOST
          value: "controller-service"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: NODE_PORT
          value: "50051"
        - name: POD_IP 
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PEER_ADDRESSES
          value: "storage-0.storage-service:50051,storage-1.storage-service:50051"
        ports:
        - containerPort: 50051