// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "blindsided.proto" (package "blindsided", syntax proto3)
// tslint:disable
import { Controller } from "./blindsided";
import type { ClusterInfoResponse } from "./blindsided";
import type { ClusterInfoRequest } from "./blindsided";
import type { GetPrimaryResponse } from "./blindsided";
import type { GetPrimaryRequest } from "./blindsided";
import type { RegisterResponse } from "./blindsided";
import type { RegisterRequest } from "./blindsided";
import { JudgeNode } from "./blindsided";
import type { PromotionResponse } from "./blindsided";
import type { PromotionRequest } from "./blindsided";
import type { HealthCheckResponse } from "./blindsided";
import type { HealthCheckRequest } from "./blindsided";
import type { ReplicationResponse } from "./blindsided";
import type { ReplicationRequest } from "./blindsided";
import type { StateResponse } from "./blindsided";
import type { StateRequest } from "./blindsided";
import type { QueryResponse } from "./blindsided";
import type { QueryRequest } from "./blindsided";
import type { CommitResponse } from "./blindsided";
import type { CommitRequest } from "./blindsided";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { BlindSided } from "./blindsided";
import type { AuctionUpdate } from "./blindsided";
import type { AuctionRequest } from "./blindsided";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { GavelResponse } from "./blindsided";
import type { GavelRequest } from "./blindsided";
import type { BidResponse } from "./blindsided";
import type { BidRequest } from "./blindsided";
import type { SearchResponse } from "./blindsided";
import type { SearchRequest } from "./blindsided";
import type { StatusResponse } from "./blindsided";
import type { StatusRequest } from "./blindsided";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { OpenResponse } from "./blindsided";
import type { OpenRequest } from "./blindsided";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service blindsided.BlindSided
 */
export interface IBlindSidedClient {
    /**
     * @generated from protobuf rpc: OpenAuction
     */
    openAuction(input: OpenRequest, options?: RpcOptions): UnaryCall<OpenRequest, OpenResponse>;
    /**
     * @generated from protobuf rpc: GetStatus
     */
    getStatus(input: StatusRequest, options?: RpcOptions): UnaryCall<StatusRequest, StatusResponse>;
    /**
     * @generated from protobuf rpc: SearchAuctions
     */
    searchAuctions(input: SearchRequest, options?: RpcOptions): UnaryCall<SearchRequest, SearchResponse>;
    /**
     * @generated from protobuf rpc: PlaceSecretBid
     */
    placeSecretBid(input: BidRequest, options?: RpcOptions): UnaryCall<BidRequest, BidResponse>;
    /**
     * @generated from protobuf rpc: DropTheGavel
     */
    dropTheGavel(input: GavelRequest, options?: RpcOptions): UnaryCall<GavelRequest, GavelResponse>;
    /**
     * @generated from protobuf rpc: JoinLiveAuction
     */
    joinLiveAuction(input: AuctionRequest, options?: RpcOptions): ServerStreamingCall<AuctionRequest, AuctionUpdate>;
}
/**
 * @generated from protobuf service blindsided.BlindSided
 */
export class BlindSidedClient implements IBlindSidedClient, ServiceInfo {
    typeName = BlindSided.typeName;
    methods = BlindSided.methods;
    options = BlindSided.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: OpenAuction
     */
    openAuction(input: OpenRequest, options?: RpcOptions): UnaryCall<OpenRequest, OpenResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<OpenRequest, OpenResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetStatus
     */
    getStatus(input: StatusRequest, options?: RpcOptions): UnaryCall<StatusRequest, StatusResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<StatusRequest, StatusResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchAuctions
     */
    searchAuctions(input: SearchRequest, options?: RpcOptions): UnaryCall<SearchRequest, SearchResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchRequest, SearchResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PlaceSecretBid
     */
    placeSecretBid(input: BidRequest, options?: RpcOptions): UnaryCall<BidRequest, BidResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<BidRequest, BidResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DropTheGavel
     */
    dropTheGavel(input: GavelRequest, options?: RpcOptions): UnaryCall<GavelRequest, GavelResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GavelRequest, GavelResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: JoinLiveAuction
     */
    joinLiveAuction(input: AuctionRequest, options?: RpcOptions): ServerStreamingCall<AuctionRequest, AuctionUpdate> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuctionRequest, AuctionUpdate>("serverStreaming", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service blindsided.JudgeNode
 */
export interface IJudgeNodeClient {
    /**
     * @generated from protobuf rpc: CommitToVault
     */
    commitToVault(input: CommitRequest, options?: RpcOptions): UnaryCall<CommitRequest, CommitResponse>;
    /**
     * @generated from protobuf rpc: QueryVault
     */
    queryVault(input: QueryRequest, options?: RpcOptions): UnaryCall<QueryRequest, QueryResponse>;
    /**
     * @generated from protobuf rpc: SyncFullState
     */
    syncFullState(input: StateRequest, options?: RpcOptions): UnaryCall<StateRequest, StateResponse>;
    /**
     * @generated from protobuf rpc: ReplicateSecret
     */
    replicateSecret(input: ReplicationRequest, options?: RpcOptions): UnaryCall<ReplicationRequest, ReplicationResponse>;
    /**
     * @generated from protobuf rpc: Heartbeat
     */
    heartbeat(input: HealthCheckRequest, options?: RpcOptions): UnaryCall<HealthCheckRequest, HealthCheckResponse>;
    /**
     * @generated from protobuf rpc: PromoteToPrimary
     */
    promoteToPrimary(input: PromotionRequest, options?: RpcOptions): UnaryCall<PromotionRequest, PromotionResponse>;
}
/**
 * @generated from protobuf service blindsided.JudgeNode
 */
export class JudgeNodeClient implements IJudgeNodeClient, ServiceInfo {
    typeName = JudgeNode.typeName;
    methods = JudgeNode.methods;
    options = JudgeNode.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CommitToVault
     */
    commitToVault(input: CommitRequest, options?: RpcOptions): UnaryCall<CommitRequest, CommitResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CommitRequest, CommitResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: QueryVault
     */
    queryVault(input: QueryRequest, options?: RpcOptions): UnaryCall<QueryRequest, QueryResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<QueryRequest, QueryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SyncFullState
     */
    syncFullState(input: StateRequest, options?: RpcOptions): UnaryCall<StateRequest, StateResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<StateRequest, StateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReplicateSecret
     */
    replicateSecret(input: ReplicationRequest, options?: RpcOptions): UnaryCall<ReplicationRequest, ReplicationResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReplicationRequest, ReplicationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Heartbeat
     */
    heartbeat(input: HealthCheckRequest, options?: RpcOptions): UnaryCall<HealthCheckRequest, HealthCheckResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<HealthCheckRequest, HealthCheckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PromoteToPrimary
     */
    promoteToPrimary(input: PromotionRequest, options?: RpcOptions): UnaryCall<PromotionRequest, PromotionResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<PromotionRequest, PromotionResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service blindsided.Controller
 */
export interface IControllerClient {
    /**
     * @generated from protobuf rpc: RegisterNode
     */
    registerNode(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: GetPrimary
     */
    getPrimary(input: GetPrimaryRequest, options?: RpcOptions): UnaryCall<GetPrimaryRequest, GetPrimaryResponse>;
    /**
     * @generated from protobuf rpc: GetClusterInfo
     */
    getClusterInfo(input: ClusterInfoRequest, options?: RpcOptions): UnaryCall<ClusterInfoRequest, ClusterInfoResponse>;
}
/**
 * @generated from protobuf service blindsided.Controller
 */
export class ControllerClient implements IControllerClient, ServiceInfo {
    typeName = Controller.typeName;
    methods = Controller.methods;
    options = Controller.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: RegisterNode
     */
    registerNode(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, RegisterResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPrimary
     */
    getPrimary(input: GetPrimaryRequest, options?: RpcOptions): UnaryCall<GetPrimaryRequest, GetPrimaryResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPrimaryRequest, GetPrimaryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetClusterInfo
     */
    getClusterInfo(input: ClusterInfoRequest, options?: RpcOptions): UnaryCall<ClusterInfoRequest, ClusterInfoResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClusterInfoRequest, ClusterInfoResponse>("unary", this._transport, method, opt, input);
    }
}
