// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "blindsided.proto" (package "blindsided", syntax proto3)
// tslint:disable
import { ClusterController } from "./blindsided";
import type { ClusterInfoResponse } from "./blindsided";
import type { ClusterInfoRequest } from "./blindsided";
import type { GetPrimaryResponse } from "./blindsided";
import type { GetPrimaryRequest } from "./blindsided";
import type { RegisterResponse } from "./blindsided";
import type { RegisterRequest } from "./blindsided";
import { StorageReplicaService } from "./blindsided";
import type { PromotionResponse } from "./blindsided";
import type { PromotionRequest } from "./blindsided";
import type { HealthCheckResponse } from "./blindsided";
import type { HealthCheckRequest } from "./blindsided";
import type { ReplicationResponse } from "./blindsided";
import type { ReplicationRequest } from "./blindsided";
import type { StateResponse } from "./blindsided";
import type { StateRequest } from "./blindsided";
import type { AuctionMutationResponse } from "./blindsided";
import type { AuctionMutationRequest } from "./blindsided";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuctionService } from "./blindsided";
import type { AuctionUpdate } from "./blindsided";
import type { AuctionRequest } from "./blindsided";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RevealAuctionResponse } from "./blindsided";
import type { RevealAuctionRequest } from "./blindsided";
import type { WithdrawBidResponse } from "./blindsided";
import type { WithdrawBidRequest } from "./blindsided";
import type { BidResponse } from "./blindsided";
import type { BidRequest } from "./blindsided";
import type { SearchAuctionsResponse } from "./blindsided";
import type { SearchAuctionsRequest } from "./blindsided";
import type { GetAuctionResponse } from "./blindsided";
import type { GetAuctionRequest } from "./blindsided";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateAuctionResponse } from "./blindsided";
import type { CreateAuctionRequest } from "./blindsided";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service blindsided.AuctionService
 */
export interface IAuctionServiceClient {
    /**
     * @generated from protobuf rpc: CreateAuction
     */
    createAuction(input: CreateAuctionRequest, options?: RpcOptions): UnaryCall<CreateAuctionRequest, CreateAuctionResponse>;
    /**
     * @generated from protobuf rpc: GetAuction
     */
    getAuction(input: GetAuctionRequest, options?: RpcOptions): UnaryCall<GetAuctionRequest, GetAuctionResponse>;
    /**
     * @generated from protobuf rpc: SearchAuctions
     */
    searchAuctions(input: SearchAuctionsRequest, options?: RpcOptions): UnaryCall<SearchAuctionsRequest, SearchAuctionsResponse>;
    /**
     * @generated from protobuf rpc: PlaceBid
     */
    placeBid(input: BidRequest, options?: RpcOptions): UnaryCall<BidRequest, BidResponse>;
    /**
     * @generated from protobuf rpc: WithdrawBid
     */
    withdrawBid(input: WithdrawBidRequest, options?: RpcOptions): UnaryCall<WithdrawBidRequest, WithdrawBidResponse>;
    /**
     * @generated from protobuf rpc: RevealAuction
     */
    revealAuction(input: RevealAuctionRequest, options?: RpcOptions): UnaryCall<RevealAuctionRequest, RevealAuctionResponse>;
    /**
     * @generated from protobuf rpc: WatchAuction
     */
    watchAuction(input: AuctionRequest, options?: RpcOptions): ServerStreamingCall<AuctionRequest, AuctionUpdate>;
}
/**
 * @generated from protobuf service blindsided.AuctionService
 */
export class AuctionServiceClient implements IAuctionServiceClient, ServiceInfo {
    typeName = AuctionService.typeName;
    methods = AuctionService.methods;
    options = AuctionService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateAuction
     */
    createAuction(input: CreateAuctionRequest, options?: RpcOptions): UnaryCall<CreateAuctionRequest, CreateAuctionResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateAuctionRequest, CreateAuctionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAuction
     */
    getAuction(input: GetAuctionRequest, options?: RpcOptions): UnaryCall<GetAuctionRequest, GetAuctionResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAuctionRequest, GetAuctionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchAuctions
     */
    searchAuctions(input: SearchAuctionsRequest, options?: RpcOptions): UnaryCall<SearchAuctionsRequest, SearchAuctionsResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchAuctionsRequest, SearchAuctionsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PlaceBid
     */
    placeBid(input: BidRequest, options?: RpcOptions): UnaryCall<BidRequest, BidResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<BidRequest, BidResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: WithdrawBid
     */
    withdrawBid(input: WithdrawBidRequest, options?: RpcOptions): UnaryCall<WithdrawBidRequest, WithdrawBidResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<WithdrawBidRequest, WithdrawBidResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RevealAuction
     */
    revealAuction(input: RevealAuctionRequest, options?: RpcOptions): UnaryCall<RevealAuctionRequest, RevealAuctionResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<RevealAuctionRequest, RevealAuctionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: WatchAuction
     */
    watchAuction(input: AuctionRequest, options?: RpcOptions): ServerStreamingCall<AuctionRequest, AuctionUpdate> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuctionRequest, AuctionUpdate>("serverStreaming", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service blindsided.StorageReplicaService
 */
export interface IStorageReplicaServiceClient {
    /**
     * @generated from protobuf rpc: ApplyAuctionMutation
     */
    applyAuctionMutation(input: AuctionMutationRequest, options?: RpcOptions): UnaryCall<AuctionMutationRequest, AuctionMutationResponse>;
    /**
     * @generated from protobuf rpc: GetAuction
     */
    getAuction(input: GetAuctionRequest, options?: RpcOptions): UnaryCall<GetAuctionRequest, GetAuctionResponse>;
    /**
     * @generated from protobuf rpc: SearchAuctions
     */
    searchAuctions(input: SearchAuctionsRequest, options?: RpcOptions): UnaryCall<SearchAuctionsRequest, SearchAuctionsResponse>;
    /**
     * @generated from protobuf rpc: SyncFullState
     */
    syncFullState(input: StateRequest, options?: RpcOptions): UnaryCall<StateRequest, StateResponse>;
    /**
     * @generated from protobuf rpc: ReplicateAuction
     */
    replicateAuction(input: ReplicationRequest, options?: RpcOptions): UnaryCall<ReplicationRequest, ReplicationResponse>;
    /**
     * @generated from protobuf rpc: Heartbeat
     */
    heartbeat(input: HealthCheckRequest, options?: RpcOptions): UnaryCall<HealthCheckRequest, HealthCheckResponse>;
    /**
     * @generated from protobuf rpc: PromoteToPrimary
     */
    promoteToPrimary(input: PromotionRequest, options?: RpcOptions): UnaryCall<PromotionRequest, PromotionResponse>;
}
/**
 * @generated from protobuf service blindsided.StorageReplicaService
 */
export class StorageReplicaServiceClient implements IStorageReplicaServiceClient, ServiceInfo {
    typeName = StorageReplicaService.typeName;
    methods = StorageReplicaService.methods;
    options = StorageReplicaService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ApplyAuctionMutation
     */
    applyAuctionMutation(input: AuctionMutationRequest, options?: RpcOptions): UnaryCall<AuctionMutationRequest, AuctionMutationResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuctionMutationRequest, AuctionMutationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAuction
     */
    getAuction(input: GetAuctionRequest, options?: RpcOptions): UnaryCall<GetAuctionRequest, GetAuctionResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAuctionRequest, GetAuctionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchAuctions
     */
    searchAuctions(input: SearchAuctionsRequest, options?: RpcOptions): UnaryCall<SearchAuctionsRequest, SearchAuctionsResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchAuctionsRequest, SearchAuctionsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SyncFullState
     */
    syncFullState(input: StateRequest, options?: RpcOptions): UnaryCall<StateRequest, StateResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<StateRequest, StateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReplicateAuction
     */
    replicateAuction(input: ReplicationRequest, options?: RpcOptions): UnaryCall<ReplicationRequest, ReplicationResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReplicationRequest, ReplicationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Heartbeat
     */
    heartbeat(input: HealthCheckRequest, options?: RpcOptions): UnaryCall<HealthCheckRequest, HealthCheckResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<HealthCheckRequest, HealthCheckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PromoteToPrimary
     */
    promoteToPrimary(input: PromotionRequest, options?: RpcOptions): UnaryCall<PromotionRequest, PromotionResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<PromotionRequest, PromotionResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service blindsided.ClusterController
 */
export interface IClusterControllerClient {
    /**
     * @generated from protobuf rpc: RegisterNode
     */
    registerNode(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: GetPrimary
     */
    getPrimary(input: GetPrimaryRequest, options?: RpcOptions): UnaryCall<GetPrimaryRequest, GetPrimaryResponse>;
    /**
     * @generated from protobuf rpc: GetClusterInfo
     */
    getClusterInfo(input: ClusterInfoRequest, options?: RpcOptions): UnaryCall<ClusterInfoRequest, ClusterInfoResponse>;
}
/**
 * @generated from protobuf service blindsided.ClusterController
 */
export class ClusterControllerClient implements IClusterControllerClient, ServiceInfo {
    typeName = ClusterController.typeName;
    methods = ClusterController.methods;
    options = ClusterController.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: RegisterNode
     */
    registerNode(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, RegisterResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPrimary
     */
    getPrimary(input: GetPrimaryRequest, options?: RpcOptions): UnaryCall<GetPrimaryRequest, GetPrimaryResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPrimaryRequest, GetPrimaryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetClusterInfo
     */
    getClusterInfo(input: ClusterInfoRequest, options?: RpcOptions): UnaryCall<ClusterInfoRequest, ClusterInfoResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClusterInfoRequest, ClusterInfoResponse>("unary", this._transport, method, opt, input);
    }
}
