# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import grpc.experimental
import warnings

from . import marketplace_pb2 as marketplace__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in marketplace_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketplaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateItem = channel.unary_unary(
                '/marketplace.Marketplace/CreateItem',
                request_serializer=marketplace__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=marketplace__pb2.CreateItemResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/marketplace.Marketplace/GetItem',
                request_serializer=marketplace__pb2.GetItemRequest.SerializeToString,
                response_deserializer=marketplace__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/marketplace.Marketplace/SearchItems',
                request_serializer=marketplace__pb2.SearchRequest.SerializeToString,
                response_deserializer=marketplace__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.UpdateItem = channel.unary_unary(
                '/marketplace.Marketplace/UpdateItem',
                request_serializer=marketplace__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=marketplace__pb2.UpdateItemResponse.FromString,
                _registered_method=True)
        self.PlaceBid = channel.unary_unary(
                '/marketplace.Marketplace/PlaceBid',
                request_serializer=marketplace__pb2.BidRequest.SerializeToString,
                response_deserializer=marketplace__pb2.BidResponse.FromString,
                _registered_method=True)
        self.JoinAuction = channel.unary_stream(
                '/marketplace.Marketplace/JoinAuction',
                request_serializer=marketplace__pb2.AuctionRequest.SerializeToString,
                response_deserializer=marketplace__pb2.AuctionUpdate.FromString,
                _registered_method=True)


class MarketplaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceBid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinAuction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketplaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=marketplace__pb2.CreateItemRequest.FromString,
                    response_serializer=marketplace__pb2.CreateItemResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=marketplace__pb2.GetItemRequest.FromString,
                    response_serializer=marketplace__pb2.GetItemResponse.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=marketplace__pb2.SearchRequest.FromString,
                    response_serializer=marketplace__pb2.SearchResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=marketplace__pb2.UpdateItemRequest.FromString,
                    response_serializer=marketplace__pb2.UpdateItemResponse.SerializeToString,
            ),
            'PlaceBid': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceBid,
                    request_deserializer=marketplace__pb2.BidRequest.FromString,
                    response_serializer=marketplace__pb2.BidResponse.SerializeToString,
            ),
            'JoinAuction': grpc.unary_stream_rpc_method_handler(
                    servicer.JoinAuction,
                    request_deserializer=marketplace__pb2.AuctionRequest.FromString,
                    response_serializer=marketplace__pb2.AuctionUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.Marketplace', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.Marketplace', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Marketplace(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.Marketplace/CreateItem',
            marketplace__pb2.CreateItemRequest.SerializeToString,
            marketplace__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.Marketplace/GetItem',
            marketplace__pb2.GetItemRequest.SerializeToString,
            marketplace__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.Marketplace/SearchItems',
            marketplace__pb2.SearchRequest.SerializeToString,
            marketplace__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.Marketplace/UpdateItem',
            marketplace__pb2.UpdateItemRequest.SerializeToString,
            marketplace__pb2.UpdateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.Marketplace/PlaceBid',
            marketplace__pb2.BidRequest.SerializeToString,
            marketplace__pb2.BidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marketplace.Marketplace/JoinAuction',
            marketplace__pb2.AuctionRequest.SerializeToString,
            marketplace__pb2.AuctionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StorageReplicaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutItem = channel.unary_unary(
                '/marketplace.StorageReplica/PutItem',
                request_serializer=marketplace__pb2.PutRequest.SerializeToString,
                response_deserializer=marketplace__pb2.PutResponse.FromString,
                _registered_method=True)
        self.QueryItems = channel.unary_unary(
                '/marketplace.StorageReplica/QueryItems',
                request_serializer=marketplace__pb2.QueryRequest.SerializeToString,
                response_deserializer=marketplace__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.SyncFullState = channel.unary_unary(
                '/marketplace.StorageReplica/SyncFullState',
                request_serializer=marketplace__pb2.StateRequest.SerializeToString,
                response_deserializer=marketplace__pb2.StateResponse.FromString,
                _registered_method=True)
        self.ReplicateLog = channel.unary_unary(
                '/marketplace.StorageReplica/ReplicateLog',
                request_serializer=marketplace__pb2.ReplicationRequest.SerializeToString,
                response_deserializer=marketplace__pb2.ReplicationResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/marketplace.StorageReplica/Heartbeat',
                request_serializer=marketplace__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=marketplace__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.PromoteToPrimary = channel.unary_unary(
                '/marketplace.StorageReplica/PromoteToPrimary',
                request_serializer=marketplace__pb2.PromotionRequest.SerializeToString,
                response_deserializer=marketplace__pb2.PromotionResponse.FromString,
                _registered_method=True)
        self.GetSnapshot = channel.unary_unary(
                '/marketplace.StorageReplica/GetSnapshot',
                request_serializer=marketplace__pb2.Empty.SerializeToString,
                response_deserializer=marketplace__pb2.SnapshotResponse.FromString,
                _registered_method=True)


class StorageReplicaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PutItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncFullState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteToPrimary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageReplicaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutItem': grpc.unary_unary_rpc_method_handler(
                    servicer.PutItem,
                    request_deserializer=marketplace__pb2.PutRequest.FromString,
                    response_serializer=marketplace__pb2.PutResponse.SerializeToString,
            ),
            'QueryItems': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryItems,
                    request_deserializer=marketplace__pb2.QueryRequest.FromString,
                    response_serializer=marketplace__pb2.QueryResponse.SerializeToString,
            ),
            'SyncFullState': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncFullState,
                    request_deserializer=marketplace__pb2.StateRequest.FromString,
                    response_serializer=marketplace__pb2.StateResponse.SerializeToString,
            ),
            'ReplicateLog': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateLog,
                    request_deserializer=marketplace__pb2.ReplicationRequest.FromString,
                    response_serializer=marketplace__pb2.ReplicationResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=marketplace__pb2.HealthCheckRequest.FromString,
                    response_serializer=marketplace__pb2.HealthCheckResponse.SerializeToString,
            ),
            'PromoteToPrimary': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteToPrimary,
                    request_deserializer=marketplace__pb2.PromotionRequest.FromString,
                    response_serializer=marketplace__pb2.PromotionResponse.SerializeToString,
            ),
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=marketplace__pb2.Empty.FromString,
                    response_serializer=marketplace__pb2.SnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.StorageReplica', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.StorageReplica', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageReplica(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PutItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.StorageReplica/PutItem',
            marketplace__pb2.PutRequest.SerializeToString,
            marketplace__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.StorageReplica/QueryItems',
            marketplace__pb2.QueryRequest.SerializeToString,
            marketplace__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncFullState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.StorageReplica/SyncFullState',
            marketplace__pb2.StateRequest.SerializeToString,
            marketplace__pb2.StateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.StorageReplica/ReplicateLog',
            marketplace__pb2.ReplicationRequest.SerializeToString,
            marketplace__pb2.ReplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.StorageReplica/Heartbeat',
            marketplace__pb2.HealthCheckRequest.SerializeToString,
            marketplace__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteToPrimary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.StorageReplica/PromoteToPrimary',
            marketplace__pb2.PromotionRequest.SerializeToString,
            marketplace__pb2.PromotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.StorageReplica/GetSnapshot',
            marketplace__pb2.Empty.SerializeToString,
            marketplace__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/marketplace.Controller/RegisterNode',
                request_serializer=marketplace__pb2.RegisterRequest.SerializeToString,
                response_deserializer=marketplace__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.GetPrimary = channel.unary_unary(
                '/marketplace.Controller/GetPrimary',
                request_serializer=marketplace__pb2.GetPrimaryRequest.SerializeToString,
                response_deserializer=marketplace__pb2.GetPrimaryResponse.FromString,
                _registered_method=True)
        self.GetClusterInfo = channel.unary_unary(
                '/marketplace.Controller/GetClusterInfo',
                request_serializer=marketplace__pb2.ClusterInfoRequest.SerializeToString,
                response_deserializer=marketplace__pb2.ClusterInfoResponse.FromString,
                _registered_method=True)


class ControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrimary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=marketplace__pb2.RegisterRequest.FromString,
                    response_serializer=marketplace__pb2.RegisterResponse.SerializeToString,
            ),
            'GetPrimary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrimary,
                    request_deserializer=marketplace__pb2.GetPrimaryRequest.FromString,
                    response_serializer=marketplace__pb2.GetPrimaryResponse.SerializeToString,
            ),
            'GetClusterInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterInfo,
                    request_deserializer=marketplace__pb2.ClusterInfoRequest.FromString,
                    response_serializer=marketplace__pb2.ClusterInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.Controller', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.Controller', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Controller(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.Controller/RegisterNode',
            marketplace__pb2.RegisterRequest.SerializeToString,
            marketplace__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrimary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.Controller/GetPrimary',
            marketplace__pb2.GetPrimaryRequest.SerializeToString,
            marketplace__pb2.GetPrimaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.Controller/GetClusterInfo',
            marketplace__pb2.ClusterInfoRequest.SerializeToString,
            marketplace__pb2.ClusterInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
